channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=24.2
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==2.2.2
  - pandas==2.2.3
  - pymongo==4.10.1
  - torch==2.6.0
name: mlflow-env
