mongo_host: "www.mongo.ca"
mongo_port: "30018"
dataset: "models_data"
collection: "TMYTS_0_2"
data_config_id: "TMYTS_PIPELINE"
mlflow_track_uri: "http://127.0.0.1:5000"
experiment: "TMYTS Explorer"
run_name: "Model GPT_0_2 - run: 01"
limit: 510000
decode_strategy: "greedy_decoding"
start_context: "Trump met for nearly two"
description: "Training GPT Model with equivalent configuration as of TMYT_0_2 V25"

# collection above is both the name of the collection
# with the data to train the model as it is also
# the config_id of the model